### ISSUE TITLE
failure 

### ISSUE THREAD

**Issue by ramezaniivar** [adaptech-cz/Tesseract4Android#64]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.googlecode.tesseract.android.TessBaseAPI.f()' on a null object reference
       at v6.a.i(:10)
       at io.flutter.embedding.engine.c.v(:122)
       at io.flutter.embedding.engine.c.w(:16)
       at io.flutter.embedding.engine.c.x(:11)
       at io.flutter.embedding.engine.c.k(:10)
       at io.flutter.embedding.engine.a.g(:31)
       at io.flutter.embedding.android.f.u(:105)
       at io.flutter.embedding.android.e.onDestroy(:18)
       at android.app.Activity.performDestroy(Activity.java:7218)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4398)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4429)
       at android.app.ActivityThread.-wrap5()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1655)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by Robyer** [comment]
This is issue in your code. It looks like you are calling some method on TessBaseAPI, but your instance is null. Maybe also try with `minifyEnabled false` in your build.gradle to see what is really being called.
